{
	"version": 1657075118,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/set3_background-sheet0.png",
		"images/set3_tiles-sheet0.png",
		"images/set3_hills-sheet0.png",
		"images/tilegreen_-sheet0.png",
		"images/tilegreen_2-sheet0.png",
		"images/pembatas-sheet0.png",
		"images/player-sheet0.png",
		"images/player-sheet1.png",
		"images/tilegreen_3-sheet0.png",
		"images/tilegreen_3-sheet1.png",
		"images/tilegreen_4-sheet0.png",
		"images/tilegreen_5-sheet0.png",
		"images/tilegreen_6-sheet0.png",
		"images/enemyflying_-sheet0.png",
		"images/enemywalking_-sheet0.png",
		"images/enemywalking_-sheet1.png",
		"images/tilegreen_7-sheet0.png",
		"images/tilegreen_8-sheet0.png",
		"images/tilegreen_9-sheet0.png",
		"images/tilegreen_9-sheet1.png",
		"images/enemyfloating_-sheet0.png",
		"images/bluegem-sheet0.png",
		"images/bluejewel-sheet0.png",
		"images/spritefont.png",
		"images/hudheart_full-sheet0.png",
		"images/btn_popup-sheet0.png",
		"images/btn_popup-sheet1.png",
		"images/key-sheet0.png",
		"images/key2-sheet0.png",
		"images/windowcopy_2-sheet0.png",
		"images/btn_pause-sheet0.png",
		"images/sprite-sheet0.png",
		"images/bannerpopup-sheet0.png",
		"images/bannerpopup-sheet1.png",
		"images/btn_resume-sheet0.png",
		"images/btn_restart-sheet0.png",
		"images/btn_exit-sheet0.png",
		"images/door_lock-sheet0.png",
		"images/door_lock-sheet1.png",
		"images/door_top-sheet0.png",
		"images/door_top-sheet1.png",
		"images/shadeddark-sheet0.png",
		"images/shadeddark2-sheet0.png",
		"images/shadeddark3-sheet0.png",
		"images/set4_background-sheet0.png",
		"images/set4_tiles-sheet0.png",
		"images/set4_hills-sheet0.png",
		"images/tilebrown_-sheet0.png",
		"images/tilebrown_2-sheet0.png",
		"images/tilebrown_3-sheet0.png",
		"images/tilebrown_3-sheet1.png",
		"images/tilebrown_4-sheet0.png",
		"images/tilebrown_4-sheet1.png",
		"images/tilebrown_5-sheet0.png",
		"images/tilebrown_5-sheet1.png",
		"images/tilebrown_6-sheet0.png",
		"images/tilebrown_6-sheet1.png",
		"images/tilebrown_7-sheet0.png",
		"images/tilebrown_7-sheet1.png",
		"images/set2_background-sheet0.png",
		"images/set2_tiles-sheet0.png",
		"images/set2_hills-sheet0.png",
		"images/tileblue_-sheet0.png",
		"images/tileblue_2-sheet0.png",
		"images/tileblue_3-sheet0.png",
		"images/tileblue_3-sheet1.png",
		"images/tileblue_4-sheet0.png",
		"images/tileblue_4-sheet1.png",
		"images/tileblue_5-sheet0.png",
		"images/tileblue_5-sheet1.png",
		"images/tileblue_6-sheet0.png",
		"images/tileblue_6-sheet1.png",
		"images/interface_menu-sheet0.png",
		"images/titleinterfacegame-sheet0.png",
		"images/btn_play-sheet0.png",
		"images/btn_about-sheet0.png",
		"images/btn_about-sheet1.png",
		"images/btn_control-sheet0.png",
		"images/btn_control-sheet1.png",
		"images/btn_musik-sheet0.png",
		"images/btn_musik-sheet1.png",
		"images/alienpink_swim-sheet0.png",
		"images/bannerpopup_mennu-sheet0.png",
		"images/bannerpopup_mennu-sheet1.png",
		"images/btn_close-sheet0.png",
		"images/btn_close-sheet1.png",
		"images/btnlevel-sheet0.png",
		"images/btn_musik_b-sheet0.png",
		"images/tileblue_7-sheet0.png",
		"images/tileblue_8-sheet0.png",
		"images/tileblue_8-sheet1.png",
		"images/tileblue_9-sheet0.png",
		"images/tileblue_9-sheet1.png",
		"images/sloganwin-sheet0.png",
		"media/collect gem.m4a",
		"media/collect gem.ogg",
		"media/hit.m4a",
		"media/hit.ogg",
		"media/collect key.m4a",
		"media/collect key.ogg",
		"media/jingle lose.m4a",
		"media/jingle lose.ogg",
		"media/jingle win.m4a",
		"media/jingle win.ogg",
		"media/click.m4a",
		"media/click.ogg",
		"media/mattoglseby - 1.m4a",
		"media/mattoglseby - 1.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}